package io.searchbox.client;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.FlowLayout;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import java.awt.GridLayout;
import java.awt.Component;

public class GUI {


  private JFrame mainFrame;
  private JPanel controlPanel;

  public GUI() {
    prepareGUI();
  }

  public static void main(String[] args) {
    GUI gui = new GUI();
    gui.showJPanelDemo();
  }

  private void prepareGUI() {
    mainFrame = new JFrame("Java Swing Examples");
    mainFrame.setSize(400, 400);


    JTabbedPane adminTabManipulate = new JTabbedPane();
    adminTabManipulate.addTab("Manipulate", manipulateTab());


    mainFrame.addWindowListener(new WindowAdapter() {
      public void windowClosing(WindowEvent windowEvent) {
        System.exit(0);
      }
    });

    controlPanel = new JPanel();
    controlPanel.setLayout(new FlowLayout());

    mainFrame.add(controlPanel);
    mainFrame.add(adminTabManipulate);
    mainFrame.setVisible(true);
  }

  private void showJPanelDemo() {

    mainFrame.setVisible(true);

  }

  private JPanel manipulateTab() {
    JPanel panel = new JPanel();
    panel.setLayout(new BoxLayout(panel, BoxLayout.PAGE_AXIS));

    JLabel indexLabel = new JLabel("Index");
    JTextField indexTextField = new JTextField();

    JPanel panelButtons = new JPanel();
    panelButtons.setLayout(new FlowLayout());
    JButton create = new JButton("Create");
    JButton update = new JButton("Update");
    JButton delete = new JButton("Delete");

    JLabel json = new JLabel("JSON String");
    JTextArea jsonArea = new JTextArea();
    JScrollPane scrollPane = new JScrollPane(jsonArea);

    JPanel authenticationProxy = new JPanel();
    authenticationProxy.setLayout(new GridLayout(1, 2));

    JPanel authentication = new JPanel();
    authentication.setLayout(new BoxLayout(authentication, BoxLayout.PAGE_AXIS));
    JLabel authLabel = new JLabel("Authentication");

    JPanel usrPanel = new JPanel();
    usrPanel.setLayout(new FlowLayout());
    JLabel usrLabel = new JLabel("Username");
    JTextField usrTxt = new JTextField("", 10);
    usrTxt.setPreferredSize(usrTxt.getPreferredSize());
    usrPanel.add(usrLabel);
    usrPanel.add(usrTxt);

    JPanel pswPanel = new JPanel();
    usrPanel.setLayout(new FlowLayout());
    JLabel pswLabel = new JLabel("Password");
    JTextField pswTxt = new JTextField("", 10);
    pswTxt.setPreferredSize(pswTxt.getPreferredSize());
    pswPanel.add(pswLabel);
    pswPanel.add(pswTxt);

    authentication.add(usrPanel);
    authentication.add(pswPanel);

    JPanel proxy = new JPanel();
    proxy.setLayout(new BoxLayout(proxy, BoxLayout.PAGE_AXIS));
    JLabel proxyLabel = new JLabel("Proxy");
    JTextField proxyTxt = new JTextField();
    proxyTxt.setPreferredSize(proxyTxt.getPreferredSize());
    proxy.add(proxyLabel);
    proxy.add(proxyTxt);

    authenticationProxy.add(authentication);
    authenticationProxy.add(proxy);


    indexTextField.setPreferredSize(indexTextField.getPreferredSize());

    panelButtons.add(create);
    panelButtons.add(update);
    panelButtons.add(delete);


    jsonArea.setPreferredSize(jsonArea.getPreferredSize());

    panel.add(indexLabel);
    panel.add(indexTextField);
    panel.add(json);
    panel.add(jsonArea);
    panel.add(scrollPane);
    panel.add(panelButtons);
    panel.add(authenticationProxy);
    panel.setAlignmentX(Component.LEFT_ALIGNMENT);

    return panel;
  }
}
