package io.searchbox.client;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JTextField;
import io.searchbox.client.config.HttpClientConfig;
import javax.swing.JTabbedPane;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JPanel;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import java.awt.GridLayout;
import java.awt.Component;
import io.searchbox.indices.CreateIndex;
import java.io.IOException;

public class GUI {


  private JFrame mainFrame;
  private JestClientFactory factory;
  private JestClient client;
  private JTextField indexTextField;

  public GUI() {
    prepareGUI();
  }

  public static void main(String[] args) {
    GUI gui = new GUI();
    gui.showJPanelDemo();
  }

  private void prepareGUI() {
    mainFrame = new JFrame("Java Swing Examples");
    mainFrame.setSize(600, 600);

    factory = new JestClientFactory();
    factory.setHttpClientConfig(new HttpClientConfig.Builder("http://localhost:9200").multiThreaded(true).build());
    client = factory.getObject();

    JTabbedPane adminTabManipulate = new JTabbedPane();
    adminTabManipulate.addTab("Manipulate", manipulateTab());
    adminTabManipulate.addTab("Search", seacrhTab());
    adminTabManipulate.addTab("Get Document", getDocument());

    mainFrame.addWindowListener(new WindowAdapter() {
      public void windowClosing(WindowEvent windowEvent) {
        System.exit(0);
      }
    });

    mainFrame.add(adminTabManipulate);
    mainFrame.setVisible(true);
  }

  private void showJPanelDemo() {

    mainFrame.setVisible(true);

  }

  private JPanel manipulateTab() {

    JPanel panel = new JPanel();
    panel.setLayout(new BoxLayout(panel, BoxLayout.PAGE_AXIS));

    JLabel indexLabel = new JLabel("Index");
    indexTextField = new JTextField();
    indexTextField.setPreferredSize(indexTextField.getPreferredSize());

    JPanel panelButtons = new JPanel();
    panelButtons.setLayout(new FlowLayout());
    JButton create = new JButton("Create");
    JButton update = new JButton("Update");
    JButton delete = new JButton("Delete");

    JLabel json = new JLabel("JSON String");
    JTextArea jsonArea = new JTextArea();
    jsonArea.setPreferredSize(jsonArea.getPreferredSize());
    JScrollPane scrollPane = new JScrollPane(jsonArea);

    JPanel authenticationProxy = new JPanel();
    authenticationProxy.setLayout(new GridLayout(1, 2));

    JPanel authentication = new JPanel();
    authentication.setLayout(new BoxLayout(authentication, BoxLayout.PAGE_AXIS));
    JLabel authLabel = new JLabel("Authentication");

    JPanel usrPanel = new JPanel();
    usrPanel.setLayout(new FlowLayout());
    JLabel usrLabel = new JLabel("Username");
    JTextField usrTxt = new JTextField("", 10);
    usrTxt.setPreferredSize(usrTxt.getPreferredSize());
    usrPanel.add(usrLabel);
    usrPanel.add(usrTxt);

    JPanel pswPanel = new JPanel();
    usrPanel.setLayout(new FlowLayout());
    JLabel pswLabel = new JLabel("Password");
    JTextField pswTxt = new JTextField("", 10);
    pswTxt.setPreferredSize(pswTxt.getPreferredSize());
    pswPanel.add(pswLabel);
    pswPanel.add(pswTxt);

    authentication.add(usrPanel);
    authentication.add(pswPanel);

    JPanel proxy = new JPanel();
    proxy.setLayout(new BoxLayout(proxy, BoxLayout.PAGE_AXIS));
    JLabel proxyLabel = new JLabel("Proxy");
    JTextField proxyTxt = new JTextField();
    proxyTxt.setPreferredSize(proxyTxt.getPreferredSize());
    proxy.add(proxyLabel);
    proxy.add(proxyTxt);

    authenticationProxy.add(authentication);
    authenticationProxy.add(proxy);

    panelButtons.add(create);
    panelButtons.add(update);
    panelButtons.add(delete);

    panel.add(indexLabel);
    panel.add(indexTextField);
    panel.add(json);
    panel.add(jsonArea);
    panel.add(scrollPane);
    panel.add(panelButtons);
    panel.add(authenticationProxy);
    panel.setAlignmentX(Component.LEFT_ALIGNMENT);

    return panel;
  }

  private JPanel seacrhTab() {
    JPanel panel = new JPanel();
    panel.setLayout(new BoxLayout(panel, BoxLayout.PAGE_AXIS));

    JLabel searchLabel = new JLabel("Search");
    JTextField searchTxtF = new JTextField();
    searchTxtF.setPreferredSize(searchTxtF.getPreferredSize());

    JLabel results = new JLabel("Results");
    JTextArea resultsArea = new JTextArea();
    resultsArea.setPreferredSize(resultsArea.getPreferredSize());

    panel.add(searchLabel);
    panel.add(searchTxtF);
    panel.add(results);
    panel.add(resultsArea);

    return panel;
  }

  private JPanel getDocument() {
    JPanel panel = new JPanel();

    return panel;
  }

  private void CreateIndex() {
    try {
      client.execute(new CreateIndex.Builder(indexTextField.getText()).build());
    } catch (IOException e) {
      System.out.println(e.getMessage());
    }
  }
}
