package io.searchbox.client;

/*Generated by MPS */

import io.searchbox.client.config.HttpClientConfig;
import io.searchbox.indices.CreateIndex;
import io.searchbox.indices.DeleteIndex;
import java.io.IOException;

public class Main {
  public static void main(String[] args) {
    JestClientFactory factory = new JestClientFactory();
    factory.setHttpClientConfig(new HttpClientConfig.Builder("http://localhost:9200").multiThreaded(true).build());
    JestClient client = factory.getObject();
    // impoting the wrong package or package that doesnot need to be imported causes issues and  
    // we need to redo everything (even deleting the entire repo) - some easy way to "delete" the imported package would be useful 
    try {
      client.execute(new CreateIndex.Builder("articles").build());
      System.out.println("Create Articles");
      client.execute(new DeleteIndex.Builder("articles").build());
      System.out.println("Delete articles");
    } catch (IOException e) {
      System.out.println("there is an exception");
      System.out.println(e.getMessage());
    }
  }
}
