package io.searchbox.client;

/*Generated by MPS */

import io.searchbox.client.config.HttpClientConfig;
import io.searchbox.indices.DeleteIndex;
import java.io.IOException;

public class Main {
  public static void main(String[] args) {
    JestClientFactory factory = new JestClientFactory();
    factory.setHttpClientConfig(new HttpClientConfig.Builder("http://localhost:9200").multiThreaded(true).build());
    JestClient client = factory.getObject();

    try {
      System.out.println("Create Articles");
      client.execute(new DeleteIndex.Builder("articles").build());
      System.out.println("Delete articles");
    } catch (IOException e) {
      System.out.println("there is an exception");
      System.out.println(e.getMessage());
    }
  }
}
