package io.searchbox.client;

/*Generated by MPS */

import io.searchbox.client.config.HttpClientConfig;

public class Main {
  public static void main(String[] args) {
    JestClientFactory factory = new JestClientFactory();
    factory.setHttpClientConfig(new HttpClientConfig.Builder("http://localhost:9200").multiThreaded(true).build());
    JestClient client = factory.getObject();
  }
}
